export const FETCH_ACTIVE_SESSION = "FETCH_ACTIVE_SESSION";
export const FETCH_ACTIVE_SESSION_SUCCESS = "FETCH_ACTIVE_SESSION_SUCCESS";
export const FETCH_ACTIVE_SESSION_FAILURE = "FETCH_ACTIVE_SESSION_FAILURE";

export const CREATE_ACTIVE_SESSION = "CREATE_ACTIVE_SESSION";
export const CREATE_ACTIVE_SESSION_SUCCESS = "CREATE_ACTIVE_SESSION_SUCCESS";
export const CREATE_ACTIVE_SESSION_FAILURE = "CREATE_ACTIVE_SESSION_FAILURE";
