export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';

export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';


export const FETCH_TASK = 'FETCH_TASK';
export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS';
export const FETCH_TASK_FAILURE = 'FETCH_TASK_FAILURE';

export const FETCH_CREATE_COMMENT_FORM = 'FETCH_CREATE_COMMENT_FORM';
export const FETCH_CREATE_COMMENT_FORM_SUCCESS = 'FETCH_CREATE_COMMENT_FORM_SUCCESS';
export const FETCH_CREATE_COMMENT_FORM_FAILURE = 'FETCH_CREATE_COMMENT_FORM_FAILURE';

export const CLAIM_TASK = 'CLAIM_TASK';
export const CLAIM_TASK_SUCCESS = 'CLAIM_TASK_SUCCESS';
export const CLAIM_TASK_FAILURE = 'CLAIM_TASK_FAILURE';


export const UNCLAIM_TASK = 'UNCLAIM_TASK';
export const UNCLAIM_TASK_SUCCESS = 'UNCLAIM_TASK_SUCCESS';
export const UNCLAIM_TASK_FAILURE = 'UNCLAIM_TASK_FAILURE';


export const COMPLETE_TASK = 'COMPLETE_TASK';
export const COMPLETE_TASK_SUCCESS = 'COMPLETE_TASK_SUCCESS';
export const COMPLETE_TASK_FAILURE = 'COMPLETE_TASK_FAILURE';

export const FETCH_TASK_ATTACHMENTS = 'FETCH_TASK_ATTACHMENTS';
export const FETCH_TASK_ATTACHMENTS_SUCCESS = 'FETCH_TASK_ATTACHMENTS_SUCCESS';
export const FETCH_TASK_ATTACHMENTS_FAILURE = 'FETCH_TASK_ATTACHMENTS_FAILURE';


export const FETCH_PROCESS_VARIABLES = 'FETCH_PROCESS_VARIABLES';
export const FETCH_PROCESS_VARIABLES_SUCCESS = 'FETCH_PROCESS_VARIABLES_SUCCESS';
export const FETCH_PROCESS_VARIABLES_FAILURE = 'FETCH_PROCESS_VARIABLES_FAILURE';


export const UPDATE_DUE_DATE = 'UPDATE_DUE_DATE';
export const UPDATE_DUE_DATE_SUCCESS = 'UPDATE_DUE_DATE_SUCCESS';
export const UPDATE_DUE_DATE_FAILURE = 'UPDATE_DUE_DATE_FAILURE';

export const CLEAR_TASK = 'CLEAR_TASK';
