
export const FETCH_PROCESS_DEFINITION_XML = 'FETCH_PROCESS_DEFINITION_XML';
export const FETCH_PROCESS_DEFINITION_XML_SUCCESS = 'FETCH_PROCESS_DEFINITION_XML_SUCCESS';
export const FETCH_PROCESS_DEFINITION_XML_FAILURE = 'FETCH_PROCESS_DEFINITION_XML_FAILURE';

export const RESET_PROCEDURE_XML = 'RESET_PROCEDURE_XML';
