export const FETCH_TASK_FORM = "FETCH_TASK_FORM";
export const FETCH_TASK_FORM_SUCCESS = "FETCH_TASK_FORM_SUCCESS";
export const FETCH_TASK_FROM_FAILURE = "FETCH_TASK_FORM_FAILURE";


export const SUBMIT_TASK_FORM = "SUBMIT_TASK_FORM";
export const SUBMIT_TASK_FORM_SUCCESS = "SUBMIT_TASK_FROM_SUCCESS";
export const SUBMIT_TASK_FORM_FAILURE = "SUBMIT_TASK_FORM_FAILURE";

export const COMPLETE_TASK_FORM = "COMPLETE_TASK_FORM";
export const COMPLETE_TASK_FORM_SUCCESS = "COMPLETE_TASK_FORM_SUCCESS";
export const COMPLETE_TASK_FORM_FAILURE = "COMPLETE_TASK_FORM_FAILURE";

export const RESET_FORM = "RESET_FORM";