export const FETCH_TASKS_ASSIGNED_TO_ME = "FETCH_TASKS_ASSIGNED_TO_ME";
export const FETCH_TASKS_ASSIGNED_TO_ME_SUCCESS = "FETCH_TASKS_ASSIGNED_TO_ME_SUCCESS";
export const FETCH_TASKS_ASSIGNED_TO_ME_FAILURE = "FETCH_TASKS_ASSIGNED_TO_ME_FAILURE";


export const FETCH_MY_GROUP_TASKS = "FETCH_MY_GROUP_TASKS";
export const FETCH_MY_GROUP_TASKS_SUCCESS = "FETCH_MY_GROUP_TASKS_SUCCESS";
export const FETCH_MY_GROUP_TASKS_FAILURE = "FETCH_MY_GROUP_TASKS_FAILURE";


export const FETCH_UNASSIGNED_TASKS = "FETCH_UNASSIGNED_TASKS";
export const FETCH_UNASSIGNED_TASKS_SUCCESS = "FETCH_UNASSIGNED_TASKS_SUCCESS";
export const FETCH_UNASSIGNED_TASKS_FAILURE = "FETCH_UNASSIGNED_TASKS_FAILURE";


export const FETCH_TASK_COUNTS = "FETCH_TASK_COUNTS";
export const FETCH_TASK_COUNTS_SUCCESS = "FETCH_TASK_COUNTS_SUCCESS";
export const FETCH_TASK_COUNTS_FAILURE = "FETCH_TASK_COUNT_FAILURE";

export const SET_TAB_INDEX = "SET_TAB_INDEX";