export const FETCH_TASKS_ASSIGNED_TO_YOU = "FETCH_TASKS_ASSIGNED_TO_YOU";
export const FETCH_TASKS_ASSIGNED_TO_YOU_SUCCESS = "FETCH_TASKS_ASSIGNED_TO_YOU_SUCCESS";
export const FETCH_TASKS_ASSIGNED_TO_YOU_FAILURE = "FETCH_TASKS_ASSIGNED_TO_YOU_FAILURE";


export const FETCH_YOUR_GROUP_TASKS = "FETCH_YOUR_GROUP_TASKS";
export const FETCH_YOUR_GROUP_TASKS_SUCCESS = "FETCH_YOUR_GROUP_TASKS_SUCCESS";
export const FETCH_YOUR_GROUP_TASKS_FAILURE = "FETCH_YOUR_GROUP_TASKS_FAILURE";


export const FETCH_UNASSIGNED_TASKS = "FETCH_UNASSIGNED_TASKS";
export const FETCH_UNASSIGNED_TASKS_SUCCESS = "FETCH_UNASSIGNED_TASKS_SUCCESS";
export const FETCH_UNASSIGNED_TASKS_FAILURE = "FETCH_UNASSIGNED_TASKS_FAILURE";

export const SET_YOUR_GROUP_TASKS_SORT_VALUE = "SET_YOUR_GROUP_TASKS_SORT_VALUE";
export const FILTER_GROUP_YOUR_TASKS_BY_NAME = "FILTER_GROUP_YOUR_TASKS_BY_NAME";

export const SET_UNASSIGNED_TASKS_SORT_VALUE = "SET_UNASSIGNED_TASKS_SORT_VALUE";
export const FILTER_GROUP_UNASSIGNED_TASKS_BY_NAME = "FILTER_GROUP_UNASSIGNED_TASKS_BY_NAME";
