export const FETCH_TASKS_ASSIGNED_TO_YOU = 'FETCH_TASKS_ASSIGNED_TO_YOU';
export const FETCH_TASKS_ASSIGNED_TO_YOU_SUCCESS = 'FETCH_TASKS_ASSIGNED_TO_YOU_SUCCESS';
export const FETCH_TASKS_ASSIGNED_TO_YOU_FAILURE = 'FETCH_TASKS_ASSIGNED_TO_YOU_FAILURE';


export const FETCH_YOUR_GROUP_TASKS = 'FETCH_YOUR_GROUP_TASKS';
export const FETCH_YOUR_GROUP_TASKS_SUCCESS = 'FETCH_YOUR_GROUP_TASKS_SUCCESS';
export const FETCH_YOUR_GROUP_TASKS_FAILURE = 'FETCH_YOUR_GROUP_TASKS_FAILURE';

export const HANDLE_UNCLAIM = 'HANDLE_UNCLAIM';

export const RESET_YOUR_TASKS = 'RESET_YOUR_TASKS';

export const GROUP_YOUR_TASKS = "GROUP_YOUR_TASKS";

export const GROUP_YOUR_TEAM_TASKS = "GROUP_YOUR_TEAM_TASKS";

export const LOAD = "LOAD";
export const LOAD_SUCCESS = "LOAD_SUCCESS";
export const LOAD_FAILURE = "LOAD_FAILURE";
