export const RESET_CASE = "RESET_CASE";
export const FIND_CASES_BY_KEY = "FIND_CASES_BY_KEY";
export const FIND_CASES_BY_KEY_SUCCESS = "FIND_CASES_BY_KEY_SUCCESS";
export const FIND_CASES_BY_KEY_FAILURE = "FIND_CASES_BY_KEY_FAILURE";

export const RESET_FORM = "REST_FORM";

export const GET_CASE_BY_KEY = "GET_CASE_BY_KEY";
export const GET_CASE_BY_KEY_SUCCESS = "GET_CASE_BY_KEY_SUCCESS";
export const GET_CASE_BY_KEY_FAILURE = "GET_CASE_BY_KEY_FAILURE";

export const GET_FORM_VERSION = "GET_FORM_VERSION";
export const GET_FORM_VERSION_SUCCESS = "GET_FORM_VERSION_SUCCESS";
export const GET_FORM_VERSION_FAILURE = "GET_FORM_VERSION_FAILURE";

export const GET_FORM_SUBMISSION_DATA = "GET_FORM_SUBMISSION_DATA";
export const GET_FORM_SUBMISSION_DATA_SUCCESS = "GET_FORM_SUBMISSION_DATA_SUCCESS";
export const GET_FORM_SUBMISSION_DATA_FAILURE = "GET_FORM_SUBMISSION_DATA_FAILURE";

export const SET_SELECTED_FORM_REFERENCE = "SET_SELECTED_FORM_REFERENCE";

export const LOAD_NEXT_SEARCH_RESULTS = "LOAD_NEXT_SEARCH_RESULTS";
export const LOAD_NEXT_SEARCH_RESULTS_SUCCESS = "LOAD_NEXT_SEARCH_RESULTS_SUCCESS";
export const LOAD_NEXT_SEARCH_RESULTS_FAILURE = "LOAD_NEXT_SEARCH_RESULTS_FAILURE";

