export const FETCH_PROCESS_DEFINITIONS = "FETCH_PROCESS_DEFINITIONS";
export const FETCH_PROCESS_DEFINITIONS_SUCCESS = "FETCH_PROCESS_DEFINITIONS_SUCCESS";
export const FETCH_PROCESS_DEFINITIONS_FAILURE = "FETCH_PROCESS_DEFINITIONS_FAILURE";
