export const FETCH_ACTIVE_SHIFT = "FETCH_ACTIVE_SHIFT";
export const FETCH_ACTIVE_SHIFT_SUCCESS = "FETCH_ACTIVE_SHIFT_SUCCESS";
export const FETCH_ACTIVE_SHIFT_FAILURE = "FETCH_ACTIVE_SHIFT_FAILURE";

export const CREATE_ACTIVE_SHIFT = "CREATE_ACTIVE_SHIFT";
export const CREATE_ACTIVE_SHIFT_SUCCESS = "CREATE_ACTIVE_SHIFT_SUCCESS";
export const CREATE_ACTIVE_SHIFT_FAILURE = "CREATE_ACTIVE_SHIFT_FAILURE";
