export default {
  type: 'form',
  tags: ['common'],
  owner: 'XXXXX',
  components: [
    {
      autofocus: false,
      id: 'id',
      input: true,
      tableView: true,
      inputType: 'text',
      inputMask: '',
      label: 'Text',
      key: 'text',
      placeholder: '',
      prefix: '',
      suffix: '',
      multiple: false,
      defaultValue: '',
      protected: false,
      unique: false,
      persistent: true,
      hidden: false,
      clearOnHide: true,
      spellcheck: true,
      validate: {
        required: false,
        minLength: '',
        maxLength: '',
        pattern: '',
        custom: '',
        customPrivate: false,
      },
      conditional: {
        show: '',
        when: null,
        eq: '',
      },
      type: 'textfield',
      labelPosition: 'top',
      tags: [],
      properties: {},
    },
    {
      id: 'canceloperation',
      autofocus: false,
      input: true,
      label: 'Cancel operation',
      tableView: false,
      key: 'canceloperation',
      size: 'md',
      leftIcon: '',
      rightIcon: '',
      block: false,
      action: 'event',
      disableOnInvalid: false,
      theme: 'primary',
      type: 'button',
      tags: [],
      conditional: {
        show: '',
        when: null,
        eq: '',
      },
      properties: {
        'success-message': 'Operation successfully cancelled',
      },
      event: 'cancel-operation',
    },
  ],
  id: 'XXXXX',
  display: 'form',
  submissionAccess: [
    {
      roles: ['5b0fa1b2769993003d6fba6f'],
      type: 'create_own',
    },
    {
      roles: ['XXXXX'],
      type: 'read_own',
    },
    {
      roles: ['XXXX'],
      type: 'update_own',
    },
    {
      roles: ['XXXXX'],
      type: 'delete_own',
    },
  ],
  title: 'Custom Button Event',
  name: 'customButtonEvent',
  path: 'custombuttonevent',
  access: [
    {
      roles: ['XXXX', 'XXXX', 'XXXXX'],
      type: 'read_all',
    },
  ],
  created: '2019-02-01T07:13:35.002Z',
  modified: '2019-02-01T07:13:35.069Z',
  machineName: 'customButtonEvent',
};
