export const FETCH_REPORTS_LIST = 'FETCH_REPORTS_LIST';
export const FETCH_REPORTS_LIST_SUCCESS = 'FETCH_REPORTS_LIST_SUCCESS';
export const FETCH_REPORTS_LIST_FAILURE = 'FETCH_REPORTS_LIST_FAILURE';
