export const FETCH_PERSON = "FETCH_PERSON";
export const FETCH_PERSON_SUCCESS = "FETCH_PERSON_SUCCESS";
export const FETCH_PERSON_FAILURE = "FETCH_PERSON_FAILURE";

export const CREATE_PERSON_RECORD = "CREATE_PERSON_RECORD";
export const CREATE_PERSON_RECORD_SUCCESS = "CREATE_PERSON_RECORD_SUCCESS";
export const CREATE_PERSON_RECORD_FAILURE = "CREATE_PERSON_RECORD_FAILURE";
