export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_FAILURE = "FETCH_COMMENTS_FAILURE";

export const CREATE_COMMENT = "CREATE_COMMENT";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";


export const FETCH_TASK = "FETCH_TASK";
export const FETCH_TASK_SUCCESS = "FETCH_TASK_SUCCESS";
export const FETCH_TASK_FAILURE = "FETCH_TASK_FAILURE";

export const FETCH_CREATE_COMMENT_FORM = "FETCH_CREATE_COMMENT_FORM";
export const FETCH_CREATE_COMMENT_FORM_SUCCESS = "FETCH_CREATE_COMMENT_FORM_SUCCESS";
export const FETCH_CREATE_COMMENT_FORM_FAILURE = "FETCH_CREATE_COMMENT_FORM_FAILURE";







