export const SELECT_ACTION = "SELECT_ACTION";

export const GET_ACTION_FORM = "GET_ACTION_FORM";
export const GET_ACTION_FORM_SUCCESS = "GET_ACTION_FORM_SUCCESS";
export const GET_ACTION_FORM_FAILURE = "GET_ACTION_FORM_FAILURE";

export const EXECUTE_ACTION = "EXECUTE_ACTION";
export const EXECUTE_ACTION_SUCCESS = "EXECUTE_ACTION_SUCCESS";
export const EXECUTE_ACTION_FAILURE = "EXECUTE_ACTION_FAILURE";

export const CLEAR_ACTION_RESPONSE= "CLEAR_ACTION_RESPONSE";

export const RESET = "RESET";
